### ISSUE TITLE
psc-package support

### ISSUE THREAD

**Issue by tmaabm** [funkia/purescript-turbine#9]
I'm currently evaluating a number of FRP-based purescript libraries but couldn't install `purescript-turbine` using `psc-package` which is, in my experience, way better than `bower`.

`purescript-hareactive` and `purescript-turbine` both do not exist in `psc-package`'s package set. Will you consider adding `psc-package` support for both of these libraries?

BTW, from reading the README(s) (including JS/TS libraries), the maintainers've done an excellent job. Hope support does not die away like with many other similar libraries.

**Comment by paldepind** [comment]
Hi @tbm206. Thank you for the suggestion. Support for os-package should definitely be added. I'll look into it to see how to add it to the package set.

**Comment by tmaabm** [comment]
Alternatively, [`spago`](https://github.com/spacchetti/spago) can be used to add the two libraries to the local package set. For example, in the `packages.dhall` file:

```purescript
let additions =
{ hareactive =
  { dependencies =
      [ "prelude"
      , "functions"
      , "maybe"
      , "partial"
      , "effect"
      , "aff"
      , "web-dom"
      , "web-uievents"
      ]
    , repo = "https://github.com/funkia/purescript-hareactive.git"
    , version = "v0.1.2"
  }
, turbine =
  { dependencies =
      [ "prelude"
      , "console"
      , "functions"
      , "record"
      , "effect"
      , "arrays"
      , "hareactive"
      , "web-html"
      , "web-events"
      , "web-uievents"
      , "typelevel-prelude"
      ]
    , repo = "https://github.com/funkia/purescript-turbine.git"
    , version = "v0.1.0"
  }
}

let upstream =
https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20191005/packages.dhall sha256:ba287d858ada09c4164792ad4e643013b742c208cbedf5de2e35ee27b64b6817

let overrides = {=}

in  additions // upstream // overrides
```
